name: CI checks
on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint-build:
    name: Sanity checks
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: go-lint
        run: make go-lint